name: client
description: ChapChap Mechanical friend

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.1.beta <3.0.0"

# Dependencies
dependencies:
  cloud_firestore: ^3.1.17
  firebase_analytics: ^9.1.9
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_crashlytics: ^2.8.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_map: ^0.14.0
  flutter_svg: ^1.1.0
  geolocator: ^8.2.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  vector_map_tiles: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  device_preview: ^1.0.0

# Flutter Framework Settings
flutter:

  # The following line ensures that the Material Icons font is included
  uses-material-design: true # TODO: Return to false for production

  # App assets:
  assets:
    - assets/images/

  #  Custom Fonts
  fonts:
    #    Icon Font
    - family: ChapChap
      fonts:
        - asset: assets/fonts/ChapChap.ttf
  #    Application Font
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

